export {
  useAdminAllocationQuery,
  useAdminAssignedStudentsQuery,
  useAdminFacultyDetailQuery,
  useAdminFacultyQuery,
  useAdminReportBacklogsQuery,
  useAdminReportGeneralQuery,
  useAdminReportIncompleteQuery,
  useAdminReportSemesterDistributionQuery,
  useAdminReportStatsQuery,
  useAdminReportToppersQuery,
  useAdminStudentDetailQuery,
  useAdminUploadStudentPhotoMutation,
  useAdminStatisticsQuery,
  useAdminStudentSummaryQuery,
  useAdminUsersQuery,
  useBulkRegisterFacultyMutation,
  useBulkRegisterStudentsMutation,
  useConfirmAllocationMutation,
  useCreateAdminUserMutation,
  useDeleteAdminUserMutation,
  useExportAllReportsMutation,
  useExportBacklogsMutation,
  useExportIncompleteReportsMutation,
  useGenerateAllocationMutation,
  useRemoveAllocationMutation,
  useResetPasswordMutation,
} from './useAdminQueries'
