export { AdminDashboardPage } from './pages/AdminDashboardPage'
export { AdminUsersPage } from './pages/AdminUsersPage'
export { AdminTeachersPage } from './pages/AdminTeachersPage'
export { AdminStudentsPage } from './pages/AdminStudentsPage'
export { AdminAllocationPage } from './pages/AdminAllocationPage'
