import { useMemo, useState } from 'react'
import { Modal, QueryState, ResponsiveDataView, type TableColumn } from '../../../../shared/ui'
import { sanitizeDisplayValue } from '../../../../shared/utils/render'
import type { AdminIncompleteProfile } from '../../api'
import {
  useAdminReportIncompleteQuery,
  useExportIncompleteReportsMutation,
} from '../../hooks'

const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8] as const
const SECTIONS = ['A', 'B'] as const

function getInitials(name: string): string {
  const clean = sanitizeDisplayValue(name)
  const parts = clean.split(/\s+/).filter(Boolean)
  if (parts.length >= 2) {
    return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase()
  }
  return clean.slice(0, 2).toUpperCase() || 'NA'
}

export function ReportIncompleteProfilesTable() {
  const [semesterFilter, setSemesterFilter] = useState<string>('')
  const [sectionFilter, setSectionFilter] = useState<string>('')
  const [viewingProfile, setViewingProfile] = useState<AdminIncompleteProfile | null>(null)

  const parsedSemester = semesterFilter ? Number(semesterFilter) : undefined
  const parsedSection = sectionFilter || undefined

  const incompleteQuery = useAdminReportIncompleteQuery(parsedSemester, parsedSection)
  const exportMutation = useExportIncompleteReportsMutation()

  // Changing either filter resets pagination to page 1 by remounting the data view.
  const dataViewKey = `${semesterFilter}-${sectionFilter}`

  const columns = useMemo<TableColumn<AdminIncompleteProfile>[]>(
    () => [
      { id: 'uid', header: 'UID', cell: (row) => <span className="mono-cell">{sanitizeDisplayValue(row.uid)}</span> },
      { id: 'name', header: 'Name', cell: (row) => sanitizeDisplayValue(row.name) },
      { id: 'year', header: 'Admission Year', cell: (row) => row.yearOfAdmission ?? 'N/A' },
      {
        id: 'missing',
        header: 'Missing Fields',
        cell: (row) => (
          <span className="reports-warning-text">
            {row.missingFields.length > 2
              ? `${row.missingFields.length} fields missing`
              : row.missingFields.length > 0
                ? row.missingFields.map((value) => sanitizeDisplayValue(value)).join(', ')
                : 'N/A'}
          </span>
        ),
      },
      {
        id: 'missing_count',
        header: 'Required Fields Not Filled',
        cell: (row) => row.missingFieldCount,
      },
      {
        id: 'actions',
        header: 'Actions',
        cell: (row) => (
          row.missingFields.length > 0 ? (
            <button
              type="button"
              className="button button--soft button--small"
              onClick={() => setViewingProfile(row)}
            >
              View Fields
            </button>
          ) : null
        ),
      },
    ],
    [],
  )

  const renderIncompleteCard = (row: AdminIncompleteProfile) => {
    const missing = row.missingFields.map((field) => sanitizeDisplayValue(field)).filter((field) => field && field !== '—')

    return (
      <div className="mobile-card">
        <div className="mobile-card__header">
          <div className="mobile-card__avatar">
            {getInitials(row.name)}
          </div>
          <div className="mobile-card__info">
            <h4 className="mobile-card__title">{sanitizeDisplayValue(row.name)}</h4>
            <p className="mobile-card__subtitle">
              <span className="reports-uid-text">{sanitizeDisplayValue(row.uid)}</span> · Profile
            </p>
          </div>
        </div>

        <div className="mobile-card__content">
          <div className="mobile-card__row">
            <span className="mobile-card__label">Type</span>
            <span className="mobile-card__value">Incomplete Profile</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Period</span>
            <span className="mobile-card__value">Admission Year {row.yearOfAdmission ?? 'N/A'}</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Generated By</span>
            <span className="mobile-card__value">Admin Panel</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Status</span>
            <div className="mobile-card__pill-list">
              <span className={`mobile-card__pill ${missing.length > 0 ? 'mobile-card__pill--warning' : 'mobile-card__pill--success'}`}>
                {missing.length > 0 ? `${missing.length} fields missing` : 'Complete'}
              </span>
            </div>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Missing Fields</span>
            <span className="mobile-card__value">
              {missing.length > 2 ? `${missing.length} fields missing` : missing.length > 0 ? missing.join(', ') : 'N/A'}
            </span>
          </div>
        </div>

        {missing.length > 0 && (
          <div className="mobile-card__actions">
            <button
              type="button"
              className="button button--soft"
              style={{ width: '100%', justifyContent: 'center' }}
              onClick={() => setViewingProfile(row)}
            >
              View Missing Fields
            </button>
          </div>
        )}
      </div>
    )
  }

  return (
    <section className="admin-section card reports-card" aria-label="Incomplete profiles report">
      <header className="reports-card__header">
        <h3>Incomplete Profiles</h3>

        <div className="reports-card__controls">
          <label className="admin-field reports-inline-field" htmlFor="incomplete-semester">
            <span>Semester</span>
            <select
              id="incomplete-semester"
              value={semesterFilter}
              onChange={(event) => setSemesterFilter(event.target.value)}
            >
              <option value="">All Semesters</option>
              {SEMESTERS.map((sem) => (
                <option key={sem} value={sem}>
                  Semester {sem}
                </option>
              ))}
            </select>
          </label>

          <label className="admin-field reports-inline-field" htmlFor="incomplete-section">
            <span>Section</span>
            <select
              id="incomplete-section"
              value={sectionFilter}
              onChange={(event) => setSectionFilter(event.target.value)}
            >
              <option value="">All Sections</option>
              {SECTIONS.map((sec) => (
                <option key={sec} value={sec}>
                  {sec}
                </option>
              ))}
            </select>
          </label>

          <button
            type="button"
            className="button button--ghost"
            onClick={() => void exportMutation.mutateAsync({ semester: parsedSemester, section: parsedSection })}
            disabled={exportMutation.isPending}
          >
            {exportMutation.isPending ? 'Exporting...' : 'Export Incomplete CSV'}
          </button>
        </div>
      </header>

      {incompleteQuery.isError ? (
        <QueryState
          tone="error"
          title="Unable to load incomplete profile report"
          description="Please retry in a moment."
          actionLabel="Retry"
          onAction={() => void incompleteQuery.refetch()}
        />
      ) : (
        <ResponsiveDataView
          key={dataViewKey}
          columns={columns}
          data={incompleteQuery.data ?? []}
          keyExtractor={(row) => row.id}
          isLoading={incompleteQuery.isPending}
          pageSize={10}
          emptyLabel="No incomplete profile rows found."
          renderMobileCard={renderIncompleteCard}
        />
      )}

      <Modal
        open={!!viewingProfile}
        onClose={() => setViewingProfile(null)}
        title="Missing Fields"
      >
        {viewingProfile && (
          <div style={{ padding: '1rem', minWidth: '300px' }}>
            <p style={{ marginBottom: '1rem', fontWeight: 500 }}>
              {viewingProfile.name} ({viewingProfile.uid}) has {viewingProfile.missingFields.length} missing fields:
            </p>
            <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {viewingProfile.missingFields.map((field) => (
                <li key={field}>{sanitizeDisplayValue(field)}</li>
              ))}
            </ul>
            <div style={{ marginTop: '1.5rem', display: 'flex', justifyContent: 'flex-end' }}>
              <button
                type="button"
                className="button button--primary"
                onClick={() => setViewingProfile(null)}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Modal>
    </section>
  )
}
