import { useMemo, useState } from 'react'
import { QueryState, ResponsiveDataView, type TableColumn } from '../../../../shared/ui'
import { sanitizeDisplayValue } from '../../../../shared/utils/render'
import type { AdminIncompleteProfile } from '../../api'
import {
  useAdminReportIncompleteQuery,
  useExportIncompleteReportsMutation,
} from '../../hooks'

function currentYearOptions() {
  const year = new Date().getFullYear()
  return Array.from({ length: 10 }, (_, index) => year - index)
}

function getInitials(name: string): string {
  const clean = sanitizeDisplayValue(name)
  const parts = clean.split(/\s+/).filter(Boolean)
  if (parts.length >= 2) {
    return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase()
  }
  return clean.slice(0, 2).toUpperCase() || 'NA'
}

export function ReportIncompleteProfilesTable() {
  const [yearFilter, setYearFilter] = useState<string>('')

  const parsedYear = yearFilter ? Number(yearFilter) : undefined
  const incompleteQuery = useAdminReportIncompleteQuery(parsedYear)
  const exportMutation = useExportIncompleteReportsMutation()

  const columns = useMemo<TableColumn<AdminIncompleteProfile>[]>(
    () => [
      { id: 'uid', header: 'UID', cell: (row) => <span className="mono-cell">{sanitizeDisplayValue(row.uid)}</span> },
      { id: 'name', header: 'Name', cell: (row) => sanitizeDisplayValue(row.name) },
      { id: 'year', header: 'Admission Year', cell: (row) => row.yearOfAdmission ?? 'N/A' },
      {
        id: 'missing',
        header: 'Missing Fields',
        cell: (row) => (
          <span className="reports-warning-text">
            {row.missingFields.length > 0 ? row.missingFields.map((value) => sanitizeDisplayValue(value)).join(', ') : 'N/A'}
          </span>
        ),
      },
    ],
    [],
  )

  const renderIncompleteCard = (row: AdminIncompleteProfile) => {
    const missing = row.missingFields.map((field) => sanitizeDisplayValue(field)).filter((field) => field && field !== '—')

    return (
      <div className="mobile-card">
        <div className="mobile-card__header">
          <div className="mobile-card__avatar" >
            {getInitials(row.name)}
          </div>
          <div className="mobile-card__info">
            <h4 className="mobile-card__title">{sanitizeDisplayValue(row.name)}</h4>
            <p className="mobile-card__subtitle">
              <span className="reports-uid-text">{sanitizeDisplayValue(row.uid)}</span> · Profile
            </p>
          </div>
        </div>

        <div className="mobile-card__content">
          <div className="mobile-card__row">
            <span className="mobile-card__label">Type</span>
            <span className="mobile-card__value">Incomplete Profile</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Period</span>
            <span className="mobile-card__value">Admission Year {row.yearOfAdmission ?? 'N/A'}</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Generated By</span>
            <span className="mobile-card__value">Admin Panel</span>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Status</span>
            <div className="mobile-card__pill-list">
              <span className={`mobile-card__pill ${missing.length > 0 ? 'mobile-card__pill--warning' : 'mobile-card__pill--success'}`}>
                {missing.length > 0 ? `${missing.length} fields missing` : 'Complete'}
              </span>
            </div>
          </div>
          <div className="mobile-card__row">
            <span className="mobile-card__label">Missing Fields</span>
            <span className="mobile-card__value">{missing.length > 0 ? missing.join(', ') : 'N/A'}</span>
          </div>
        </div>

      </div>
    )
  }

  return (
    <section className="admin-section card reports-card" aria-label="Incomplete profiles report">
      <header className="reports-card__header">
        <h3>Incomplete Profiles</h3>

        <div className="reports-card__controls">
          <label className="admin-field reports-inline-field" htmlFor="incomplete-year">
            <span>Year</span>
            <select
              id="incomplete-year"
              value={yearFilter}
              onChange={(event) => setYearFilter(event.target.value)}
            >
              <option value="">All years</option>
              {currentYearOptions().map((year) => (
                <option key={year} value={year}>
                  {year}
                </option>
              ))}
            </select>
          </label>

          <button
            type="button"
            className="button button--ghost"
            onClick={() => void exportMutation.mutateAsync({ year: parsedYear })}
            disabled={exportMutation.isPending}
          >
            {exportMutation.isPending ? 'Exporting...' : 'Export Incomplete CSV'}
          </button>
        </div>
      </header>

      {incompleteQuery.isError ? (
        <QueryState
          tone="error"
          title="Unable to load incomplete profile report"
          description="Please retry in a moment."
          actionLabel="Retry"
          onAction={() => void incompleteQuery.refetch()}
        />
      ) : (
        <ResponsiveDataView
          columns={columns}
          data={incompleteQuery.data ?? []}
          keyExtractor={(row) => row.id}
          isLoading={incompleteQuery.isPending}
          pageSize={10}
          emptyLabel="No incomplete profile rows found."
          renderMobileCard={renderIncompleteCard}
        />
      )}
    </section>
  )
}
